trigger:
- main

variables:
- group: 'IaC_JFC'
- name : awsCredential
  value: ServiceConnectionJFC

stages:

- stage: Deploy_vpc
  jobs:
  - job: Terraform_vpc
    steps:
    - template: terraform-steps.yaml
      parameters:
        workingDir: 'vpc'
        planFile: 'vpc.plan'
        group: 'IaC_JFC'


- stage: Deploy_eks
  dependsOn: Deploy_vpc
  jobs:
  - job: Terraform_eks
    steps:
    - template: terraform-steps.yaml
      parameters:
        workingDir: 'eks'
        planFile: 'eks.plan'
        group: 'IaC_JFC'

- stage: Deploy_s3
  jobs:
  - job: Terraform_vpc
    steps:
    - template: terraform-steps.yaml
      parameters:
        workingDir: 's3'
        planFile: 's3.plan'
        group: 'IaC_JFC'

- stage: Deploy_route53
  jobs:
  - job: Terraform_vpc
    steps:
    - template: terraform-steps.yaml
      parameters:
        workingDir: 'route53'
        planFile: 'route53.plan'
        group: 'IaC_JFC'

- stage: Deploy_cloudfront
  jobs:
  - job: Terraform_s3
    steps:
    - template: terraform-steps.yaml
      parameters:
        workingDir: 'cloudfront'
        planFile: 'cloudfront.plan'
        group: 'IaC_JFC'