trigger:
- main

variables:
- group: 'IaC_retoTecnico_${{ parameters.environment }}'
- name : awsCredential
  value: ServiceConnection

parameters:
- name: environment
  displayName: "Selecciona el Ambiente"
  type: string
  default: dev
  values:
    - dev
    - stg
    - prod

stages:

- stage: Deploy_vpc
  jobs:
  - job: Terraform_vpc
    steps:
    - template: terraform-steps.yaml
      parameters:
        workingDir: 'vpc'
        planFile: 'vpc.plan'
        group: 'IaC_retoTecnico_${{ parameters.environment }}'


- stage: Deploy_eks
  dependsOn: Deploy_vpc
  jobs:
  - job: Terraform_eks
    steps:
    - template: terraform-steps.yaml
      parameters:
        workingDir: 'eks'
        planFile: 'eks.plan'
        group: 'IaC_retoTecnico_${{ parameters.environment }}'

- stage: Deploy_s3
  jobs:
  - job: Terraform_vpc
    steps:
    - template: terraform-steps.yaml
      parameters:
        workingDir: 's3'
        planFile: 's3.plan'
        group: 'IaC_retoTecnico_${{ parameters.environment }}'
